[package]
name = "aloroid/plasma"
description = "Plasma with types n more"
version = "0.4.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"example",
	"docs",
	"Packages",
	".moonwave",
	"build",
	"pages",
	"tests",
	"stories",
	"plasma.rbxm",
	"roblox.toml",
]

[dependencies]
TestEZ = "roblox/testez@0.4.1"
